- lib/eventstore.js
- test/eventstoreTest.js
In getFromSnapshot if there are no events in the stream after the snapshot, the
returned stream object had a lastRevision of -1 which causes the next event to
be created with a revision number of 0, breaking the event stream. This fix
set's the last revision equal to the snapshot's revision number.
> Fix stream revision # after snapshot

- lib/databases/inmemory.js
- lib/databases/mongodb.js
- lib/databases/tingodb.js
- package.json
**Massive mongodb performance improvements**
Before: very low throughput, bad scalability in number of aggregates and number of events, full CPU load consumed by mongod process due to inefficient event fetching
Now: much improved throughput (> factor 10), good scalability, moderate CPU load
All tests are green (run with mongo 2.0.24 driver).
> mongodb and inmemory performance improvements

- lib/databases/mongodb.js
You can add now an authentication database for mongodb by initialising the eventstore:
```
var es = require('eventstore')({
type: 'mongodb',
host: 'localhost',                          // optional
port: 27017,                                // optional
dbName: 'eventstore',                       // optional
eventsCollectionName: 'events',             // optional
snapshotsCollectionName: 'snapshots',       // optional
transactionsCollectionName: 'transactions', // optional
timeout: 10000                              // optional
// authSource: 'authedicationDatabase',        // optional
// username: 'technicalDbUser',                // optional
// password: 'secret'                          // optional
});
```
> Support authSource authentication option in mongodb

- .travis.yml
- README.md
- lib/databases/elasticsearch.js
- package.json
- test/eventstoreTest.js
- test/storeTest.js
Elasticsearch can now be used as the storage of the event store:
```
var es = require('eventstore')({
type: 'elasticsearch',
host: 'localhost:9200',
indexName: 'eventstore',
eventsTypeName: 'events',
snapshotsTypeName: 'snapshots',
log: 'warning',
maxSearchResults: 10000
});
```
Note that the `maxSearchResults` setting here is used when all (limit -1) events are retrieved. This is because Elasticsearch doesn't support retrieving an unlimited amount of results.
> Add Elasticsearch db support

- lib/eventstore.js
- test/eventstoreTest.js
For streamRevision, for example, because 1st revision value is 0, streamRevision is not copied in the payload : the value is bypassed because of the test in the `if` statement
> Fix eventmappings when value is empty or 0

- lib/databases/mongodb.js
__Reason__
The index is needed when using this api call:
```js
store.getEvents({aggregate:'my-aggregate', skip, limit, cb)
```
_(the values of skip and limit don't matter)_
The query above is handled by this call to mongodb client:
```
this.events.find(findStatement, { sort: [
['commitStamp', 'asc'],
['streamRevision', 'asc'],
['commitSequence', 'asc']] }).toArray(function (err, res) {
```
https://github.com/adrai/node-eventstore/blob/v1.7.3/lib/databases/mongodb.js#L327
Without the index, MongoDb has to sort in memory, which works fine for few events, but with enough events you'll hit the ceiling and get an error, like this:
> Plan executor error during find: Overflow sort stage buffered data usage of 33554808 bytes exceeds internal limit of 33554432 bytes
> MongoDb: Add index used when querying for all events for an aggregate type

- lib/databases/inmemory.js
Fix for #66 
Only `in-memory` is affected so risk of regression should be minimal.
> keep events immutable: always deep clone events from in memory store

- README.md
- lib/databases/mongodb.js
Quick PR for #68. 
Use can now pass in a [mongo connection string](https://docs.mongodb.com/manual/reference/connection-string/) which is a lot more powerful than passing in individual host/port or servers.
As discussed in the issue, this is especially useful for supporting different environments (dev/prod etc).
Implemented by converting host/port/db/auth/servers etc to a connection string and using MongoClient.connect, which is more simple than the deprecated way of creating ReplSet/Servet etc depending on the parameters.
All tests pass except some unrelated elasticsearch/redis tests which I do not have installed.
> Support mongo connection string

- lib/eventDispatcher.js
- test/eventDispatcherTest.js
This resolves an issue where the maximum call stack size could be hit when processing 1000s of undispatched events on startup
> Fix - large numbers of undispatched events

- .gitignore
- lib/databases/dynamodb.js
- package.json
- test/eventstoreTest.js
- test/storeTest.js
DynamoDB tests can be run against a [local DynamoDB instance](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html) and by making sure that the following environment variables are set:
AWS_ACCESS_KEY_ID=anything_you_like
AWS_SECRET_ACCESS_KEY=anything-you-like
AWS_REGION=doesnt-matter-4-local
AWS_DYNAMODB_ENDPOINT=http://localhost:8000
The first three values are arbitrary unless you want to connect to an existing AWS account the last one is required to point to the host:port combination of where you're running DynamoDB local.
If you want to connect to an existing AWS account, make sure the first 3 variables are properly set and the fourth one (`AWS_DYNAMODB_ENDPOINT`) doesn't exist.
I use DynamoDB local for development and then AWS for good measure. Running …
> adding dynamodb store implementation

- lib/eventstore.js
This change avoids the eventstream to lose events from the uncommittedEvents list that were added in between the èventstore.commit` and `store.addEvents` call by only working on a copy of those.
Fixes #84
> Prevent uncommittedEvents to be overwritten accidentally

- README.md
- lib/databases/dynamodb.js
- package.json
Because DynamoDB has the DynamDB.Streams feature which allows streaming output of all changes to a table it is cheaper to use this feature than UndispatchedEvents. So I've added a flag to disable the use of the UndispatchedEvents tables for those who prefer to read from the stream instead.
> Optional dispatch table

- README.md
- lib/databases/elasticsearch.js
Sometimes it's required to manually create ES client, e.g. Amazon AWS ElasticSearch service client or some additional options should be set (e.g. timeouts). So I add an option to pass existed ES client object into the storage via options.
> ability to use custom elasticsearch client in the elasticsearch storage

- lib/databases/redis.js
snapshots where loaded all together to only use the latest with revMax === -1, causing performance issues
now snapshots are loaded from redis recursively to find the one that match revMax option.
see 
See https://github.com/adrai/node-eventstore/issues/24
> redis snapshots are retrieved recursively to match 'max revision' option

- lib/databases/redis.js
- lib/databases/redis/commit.lua
- test/eventstoreTest.js
- test/storeTest.js
instead of using last event revision, redis use a lua script so that revision is always accurate
Fixes #90
> improve event revision accuracy in redis, to avoid revisions duplications for an aggregate

- lib/databases/redis/commit.lua
- test/storeTest.js
streamRevision field of an event calculated in lua script was not casted to an int
it could cause a sorting issue of events when they are loaded
> fix calculated streamRevision for redis to avoid events sorting issues

- lib/databases/dynamodb.js
DynamoDB Streams outputs events in the order they were received, so if events are committed out of order the stream will publish the events in the wrong order. 
AddEvents has been changed to use sequential async methods instead of parallel to correct out of order events in the stream.
> changed addEvents to use sequential async methods instead of parallel

- lib/base.js
- package.json
Hi there,
This week a new version of the [uuid](https://github.com/kelektiv/node-uuid) module got released. The old module which was available by the name [node-uuid](https://www.npmjs.com/package/node-uuid) got deprecated and will show error message upon every install of the module.
To get rid of those install errors I've created this **automated pull request**. I've run some checks against your code base to test whether you're using one of the [deprecated apis](https://github.com/kelektiv/node-uuid/commit/5ae7287fc935eb55ef39133e4be17ef623ca000e), but this isn't the case.
Please test the changes against your code. I didn't run any tests and therefore can't guarantee that it isn't breaking. You can also just close this pr if you don't want to update your module.
In case there's already …
> Update uuid to version 3.0.0

- lib/databases/redis.js
- lib/event.js
- lib/eventStream.js
- lib/eventstore.js
- test/storeTest.js
The lua script has been removed, and the stream revision consistency is based on a redis `INCR`, which is enough to ensure that the revision is the right one.
It was also necessary to re apply mappings once the revision has been reset.
Fixes #96
> Fix empty array conversion due to Lua json decode

- README.md
- lib/base.js
- lib/databases/elasticsearch.js
- lib/databases/inmemory.js
- lib/databases/mongodb.js
- lib/databases/redis.js
- lib/databases/tingodb.js
- lib/eventstore.js
- test/eventstoreTest.js
- test/storeTest.js
Feature needs `maxSnapshotsCount` to be activated. It configures the number of snapshots to keep. Others are cleaned whenever a new snapshot is created for an aggregate.
Feature is implemented for mongodb, redis, elasticsearch, tingodb, and inmemory stores.
Closes #100
> Clean snapshots automatically whenever activated

- lib/databases/dynamodb.js
Passing configuration values on initialization to the DynamoDB document client did not work since the DocumentClient constructor did not correctly receive the DynamoDB client as outlined in the SDK docs.
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html#constructor-property
This should be fixed now with this commit, being able to pass the init values as part of the configuration rather than the global AWS config object (env variables).
> Fixing dynamodb DocumentClient initialization

- lib/databases/dynamodb.js
Currently the condition expression that is supposed to protect against concurrency violations will only be invoked when both commits are created using the exact same commit timestamp. This is because condition expressions are only checked against items with the same key. The fix for this is to remove the timestamp from the key, leaving the aggregateId, aggregate, context and streamRevision.
> Fix DynamoDB concurrency

- README.md
- lib/databases/dynamodb.js
At present this option will only be used at the time of events table creation and will not apply to a pre-existing events table
> Optionally enable dynamodb stream on the events table

- lib/databases/dynamodb.js
PR #110 correctly removed the commitStamp from the derived rowKey value in the dynamodb provider to resolve a concurrency issue, however it has also revealed an issue with the events table sort key/range key (provided by the derived "rowKey" value)
Queries/Scans against aggregates with more than 10 revisions are currently being returned with an incorrect sort order from the dynamodb events table due to the stream revision value not being padded.
e.g. (current)
| aggregateId  | rowKey |
| ------------- | ------------- |
| myagg1 | ::0 |
| myagg1 | ::1 |
| myagg1 | ::10 |
| myagg1 | ::2 |
| myagg1 | ::3 |
...
| myagg1 | ::9 |
e.g. (with fix by padding the stream revision value during rowKey derivation)
| aggregateId  | rowKey |
| ------------- | ------------- |
| myagg1 | ::000 |
| myagg1 | …
> Fix sort key/range key ordering in dynamodb events table

- lib/eventstore.js
- test/eventstoreTest.js
The bug fix to issue #112 left the events.next() function in the wrong scope. So if you call es.getEvents((err, events) => {...}) without query and/or skip, limit parameters the events.next() won't receive the parameter cleanup and behave in an unpredictable way.
> events.next() is placed in the wrong scope

- lib/eventstore.js
- test/eventstoreTest.js
Reverts adrai/node-eventstore#116
> Revert "events.next() is placed in the wrong scope"

- lib/databases/dynamodb.js
During concurrent operations there is no guarantee that a table is not created between checking it's existance (using describeTable) and making the call to create the table. Currently, when this happens, it is erroring out with the 'Cannot create preexisting table' error.
Even ensuring that the init promise is resolved before calling it again is not enough because the call to describeTable is eventually consistent.
The fix is to swallow the error when the table already exists. At the end of the day, the system is in the state that we want it to be anyway (the table exists).
> Fix concurrency issue in createTableIfNotExists (DynamoDB adapter)

- lib/databases/redis.js
- test/storeTest.js
If you have an `EventStore` instance of type `redis` including a non-zero `maxSnapshotsCount` (for example, `maxSnapshotsCount: 5`),
When you have fewer than 5 snapshots (i.e. 0), and you call something like:
```js
es.createSnapshot(snap, (err) => {
if (err) { console.log(err); /*handle err*/ }
// ...etc.
})
```
Then you will see this error:
```
ReplyError: ERR wrong number of arguments for 'del' command
/app/node_modules/redis-parser/lib/parser.js in parseError at line 193:12
```
(NOTE: the snapshot *does* get created correctly, but then the return value errors because `cleanSnapshots` fails).
You can call `es.createSnapshot(snap, cb)` without the error from `cleanSnapshots`.
@adrai hope this is helpful, and let me know if you see any changes you'd like made. Thanks.
(Fixes #126)
> Fix store.cleanSnapshots for redis implementation
