adrai/node-eventstore

- package.json
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build5995810683676757849">David Update as a Service - Tachikoma.io</a>
> Exec tachikoma update 20150420065116

- package.json
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6003420823893776480">David Update as a Service - Tachikoma.io</a>
> Exec tachikoma update 20150511065117

- package.json
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6008494254225432785">David Update as a Service - Tachikoma.io</a>
> Exec tachikoma update 20150525065123

- package.json
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6013567680321696759">David Update as a Service - Tachikoma.io</a>
> Exec tachikoma update 20150608065115

- lib/databases/azuretable.js
- test/eventstoreTest.js
- test/storeTest.js
Adding getEventsSince function for azuretable #35
> Adding getEventsSince function for azuretable #35

- package.json
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6023714548273250085">David Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6023714548273250085">2015-06-28 Updated permissions - Tachikoma.io</a>
> Exec tachikoma update 20150706065126

- package.json
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6028787971120794123">David Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6028787971120794123">2015-06-28 Updated permissions - Tachikoma.io</a>
> Exec tachikoma update 20150720065122

- package.json
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6033861406080435499">David Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6033861406080435499">2015-06-28 Updated permissions - Tachikoma.io</a>
> Exec tachikoma update 20150803065137

- package.json
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6036398115764807542">David Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6036398115764807542">2015-06-28 Updated permissions - Tachikoma.io</a>
> Exec tachikoma update 20150810065127

- package.json
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6064301982992490254">David Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6064301982992490254">2015-06-28 Updated permissions - Tachikoma.io</a>
> Exec tachikoma update 20151026065117

- package.json
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6089669134562934654">David Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6089669134562934654">2015-06-28 Updated permissions - Tachikoma.io</a>
> Exec tachikoma update 20160104065142

- package.json
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6092205850359153886">David Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6092205850359153886">2015-06-28 Updated permissions - Tachikoma.io</a>
> Exec tachikoma update 20160111065129

- lib/databases/azuretable.js
- package.json
- test/eventstoreTest.js
- test/storeTest.js
Update azure-storage dependencies
Adding getLastEvent support in azure table provider
Enable tests for azure table provider
> Update azure-storage dependencies

- README.md
- lib/databases/dynamodb.js
as promised here are the revisions and cleanup after the initial PR for dynamodb
> cleanup, revisions, hardening of dynamodb provider

- lib/databases/dynamodb.js
changed conditional expression to prevent overwriting by aggregateid + version + aggregate + context at the database level for dynamodb
> Ensuring concurrency

- lib/eventStream.js
fixed adrai/node-eventstore#98
> Handled the exception described the issue #98 where events is []

- lib/databases/dynamodb.js
Dynamodb was erroring out on table creation
> Fixed TypeError: "callback" argument must be a function

- lib/databases/dynamodb.js
I'm really sorry but I messed up on my previous pull-request. This is the fix.
> fix commit 7b460dd12c582a49a8bcd6e0fe90c979054c4a28

- README.md
supply missing snapshot on callback argument
> fix example of snapshot api

- lib/databases/mongodb.js
PR for to correct deprecation warning in mongo https://github.com/adrai/node-eventstore/issues/161
> Added new default configuration option for mongo db: useUnifiedTopology

- lib/databases/mongodb.js
resolving #168 
I'm not sure about that last line of code I commented. I couldn't tested that part but in my test case it looks OK.
> Fixing omitting & duplication issue on mongoDB streamEventsByRevision
